### ISSUE TITLE
Exception on seed database

### ISSUE THREAD

**Issue by blob84** [marketplacekit/marketplacekit#126]
Hello when I try to seed the db I get this error:
```
Spatie\Permission\Exceptions\PermissionDoesNotExist  : There is no permission named `edit listing` for guard `web.


  at /var/www/html/marketplacekit/vendor/spatie/laravel-permission/src/Exceptions/PermissionDoesNotExist.php:11
      class PermissionDoesNotExist extends InvalidArgumentException
      {
          public static function create(string $permissionName, string $guardName = '')
         {
          return new static("There is no permission named `{$permissionName}` for guard `{$guardName}`.");
        }
     
         public static function withId(int $permissionId)
         {

  Exception trace:

  1   Spatie\Permission\Exceptions\PermissionDoesNotExist::create("edit listing", "web")
      /var/www/html/marketplacekit/vendor/spatie/laravel-permission/src/Models/Permission.php:96

  2   Spatie\Permission\Models\Permission::findByName("edit listing", "web")
      /var/www/html/marketplacekit/vendor/spatie/laravel-permission/src/Traits/HasPermissions.php:327

```
how can I fix?

**Comment by lafree777** [comment]
Also a problem with  
php artisan db:seed - Exception on seed database

**Comment by zacharyk88** [comment]
Having this same issue

**Comment by MPSimon** [comment]
try:

1 - php artisan migrate:rollback
2- php artisan lada-cache:disable
3 -php artisan migrate
4- php artisan db:seed

Then you can login in the browser as admin with the defaults credentials:

user:admin@example.com
password:changeme

**Comment by thanphl** [comment]
I had this error while installing marketplacekit as well, this is how I resolved it:

The issue happens in _database/seeds/RolesAndPermissionsSeeder.php_ when running at:
`<>->givePermissionTo(<>)`

Stacktrace:
```
[2020-12-11 10:35:59] production.ERROR: There is no permission named `edit listing` for guard `web`. {"exception":"[object] (Spatie\\Permission\\Exceptions\\PermissionDoesNotExist(code: 0): There is no permission named `edit listing` for guard `web`. at /media/thanphl/Working/workspace/marketplacekit/vendor/spatie/laravel-permission/src/Exceptions/PermissionDoesNotExist.php:11)
[stacktrace]
#0 /media/thanphl/Working/workspace/marketplacekit/vendor/spatie/laravel-permission/src/Models/Permission.php(96): Spatie\\Permission\\Exceptions\\PermissionDoesNotExist::create()
#1 /media/thanphl/Working/workspace/marketplacekit/vendor/spatie/laravel-permission/src/Traits/HasPermissions.php(327): Spatie\\Permission\\Models\\Permission::findByName()
#2 /media/thanphl/Working/workspace/marketplacekit/vendor/spatie/laravel-permission/src/Traits/HasPermissions.php(265): Spatie\\Permission\\Models\\Role->getStoredPermission()
#3 [internal function]: Spatie\\Permission\\Models\\Role->Spatie\\Permission\\Traits\\{closure}()
#4 /media/thanphl/Working/workspace/marketplacekit/vendor/laravel/framework/src/Illuminate/Support/Collection.php(932): array_map()
#5 /media/thanphl/Working/workspace/marketplacekit/vendor/spatie/laravel-permission/src/Traits/HasPermissions.php(266): Illuminate\\Support\\Collection->map()
#6 /media/thanphl/Working/workspace/marketplacekit/database/seeds/RolesAndPermissionsSeeder.php(33): Spatie\\Permission\\Models\\Role->givePermissionTo()
#7 [internal function]: RolesAndPermissionsSeeder->run()
```

_The seeder already had clear cache key, so you do not need to run it again, but free to run so_
![image](https://user-images.githubusercontent.com/4957750/101973562-80806f00-3c6b-11eb-8ebc-ebbbca2030ad.png)


Fix:

- Open `vendor/spatie/laravel-permission/src/Models/Permission.php`
- Update method `public static function findByName(string $name, $guardName = null)`
- Replace:
```
$permission = static::getPermissions()->filter(function ($permission) use ($name, $guardName) {
            return $permission->name === $name && $permission->guard_name === $guardName;
        })->first();
```
with
```
$permission = Permission::where('name', $name)->where('guard_name', $guardName)->first();
```
Final code

![image](https://user-images.githubusercontent.com/4957750/101973480-06e88100-3c6b-11eb-97e3-87512c655d95.png)

* Change assign _admin_ role here as well since method _assignRole_ has same issue with _givePermissionTo_, it can run with id of role instead of string value
![image](https://user-images.githubusercontent.com/4957750/101973508-40b98780-3c6b-11eb-8d20-fe86928ac666.png)

Hope this could help

**Comment by antonioconselheiro** [comment]
Nice thanphl, it solved for me, I had the same problem here
